name: aws_asdi_cities_smsl
channels:
- conda-forge
- defaults
dependencies:
- python>=3.8
- numpy
- matplotlib
- datetime
- jupyter
- boto
- boto3
- requests
- seaborn
- geopandas
- shapely
- pandas
- json